# Generated by Django 5.2.1 on 2025-05-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
