# Generated by Django 5.2.1 on 2025-05-30 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_body_alter_car_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='body',
            old_name='name',
            new_name='body',
        ),
    ]
