# Generated by Django 5.2.1 on 2025-05-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_car_transmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(default='Available', max_length=200, null=True),
        ),
    ]
