# Generated by Django 5.2.1 on 2025-05-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_car_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
